###
# Initial Center constants
# 
# The filters shift the input image as such the actual cordinates of the center need to be determined.
###
center_x = 0
center_y = 0

###
# AXI ADDRESS
###
AXI_ADDR_AXIS_SWITCH = 0x40000000
AXI_LENGTH_AXIS_SWITCH = 65536

AXI_ADDR_CIRCLE_DETECT = 0x40010000
AXI_LENGTH_CIRCLE_DETECT = 4096
AXI_CIRCLE_DETECT_X_REG = 0x4
AXI_CIRCLE_DETECT_Y_REG = 0x0




AXI_ADDR_PWM_CONTROLLER = 0x40020000
AXI_LENGTH_PWM_CONTROLLER = 65536


AXI_ADDR_STREAM_CROP = 0x40030000
AXI_LENGTH_STREAM_CROP = 4096
AXI_LENGTH_LIMIT_LOWER_X = 0x0
AXI_LENGTH_LIMIT_UPPER_X = 0x4
AXI_LENGTH_LIMIT_LOWER_Y = 0x8
AXI_LENGTH_LIMIT_UPPER_Y = 0xc


AXI_PWM_CONTROLLER_0 = 0x4
OFFSET_PWM_CONTROLLER_0 = 0

AXI_PWM_CONTROLLER_1 = 0x4
OFFSET_PWM_CONTROLLER_1 = 10

AXI_PWM_CONTROLLER_2 = 0x4
OFFSET_PWM_CONTROLLER_2 = 20

AXI_PWM_CONTROLLER_3 = 0x8
OFFSET_PWM_CONTROLLER_3 = 0

AXI_PWM_CONTROLLER_4 = 0x8
OFFSET_PWM_CONTROLLER_4 = 10

AXI_PWM_CONTROLLER_5 = 0x8
OFFSET_PWM_CONTROLLER_5 = 20

###
#
# AXIS SWITCH CONSTANTS
#
###
DISABLED             = 0x80000000
 
INPUT          = 0
OUTPUT         = 0
SMOOTHING_1    = 1
EDGE           = 2
CIRCLE_DETECT  = 3
SMOOTHING_2    = 4
SMOOTHING_3    = 5
SMOOTHING_4    = 6
CROP_BUTTON    = 0
CROP_PIPELINE  = 8


TEST_SIGNAL_GEN = 7
COLOR_TEST = 8