-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_21_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_in_24_TVALID : IN STD_LOGIC;
    stream_out_32_TREADY : IN STD_LOGIC;
    stream_out_32_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_out_32_TVALID : OUT STD_LOGIC;
    stream_out_32_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_32_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_32_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_32_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_in_24_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_in_24_TREADY : OUT STD_LOGIC;
    stream_in_24_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_24_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_24_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_24_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_21_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal delayed_last_reg_135 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_8_reg_146 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_497 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_7_reg_514 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op49_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal delayed_last_reg_135_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal last_8_reg_146_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op98_write_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal tmp_last_V_8_reg_529 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op69_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal stream_out_32_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal stream_in_24_TDATA_blk_n : STD_LOGIC;
    signal ap_phi_mux_delayed_last_phi_fu_138_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_last_8_phi_fu_150_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_predicate_op30_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op90_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal last_2_3872_reg_175 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_reg_485 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_user_V_reg_491 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_197_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_10_reg_502 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_op35_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_predicate_op97_write_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_user_V_9_reg_508 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_11_reg_519 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal tmp_user_V_10_reg_524 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pixel_data_V_1_reg_533 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_5_reg_538 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pixel_data_V_2_reg_548 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_7_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_reg_558 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_last_2_3871_phi_fu_162_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_last_2_3872_reg_175 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_fu_88 : STD_LOGIC_VECTOR (95 downto 0);
    signal p_Result_18_fu_346_p5 : STD_LOGIC_VECTOR (95 downto 0);
    signal p_Result_15_fu_269_p5 : STD_LOGIC_VECTOR (95 downto 0);
    signal p_Result_12_fu_240_p5 : STD_LOGIC_VECTOR (95 downto 0);
    signal p_Result_9_fu_211_p5 : STD_LOGIC_VECTOR (95 downto 0);
    signal p_Val2_9_fu_92 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_20_fu_364_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_17_fu_291_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_14_fu_260_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_11_fu_231_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_10_fu_96 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_19_fu_355_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_16_fu_281_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_13_fu_251_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_10_fu_222_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_pixel_data_V_fu_392_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal p_Result_s_fu_387_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_512 : BOOLEAN;
    signal ap_condition_516 : BOOLEAN;
    signal ap_condition_262 : BOOLEAN;
    signal ap_condition_526 : BOOLEAN;
    signal ap_condition_532 : BOOLEAN;
    signal ap_condition_537 : BOOLEAN;
    signal ap_condition_541 : BOOLEAN;
    signal ap_condition_522 : BOOLEAN;
    signal ap_condition_547 : BOOLEAN;
    signal ap_condition_551 : BOOLEAN;
    signal ap_condition_555 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component pixel_pack_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pixel_pack_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    delayed_last_reg_135_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    delayed_last_reg_135 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_516)) then 
                    delayed_last_reg_135 <= last_8_reg_146;
                end if;
            end if; 
        end if;
    end process;

    last_2_3872_reg_175_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_262)) then
                if (((last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0))) then 
                    last_2_3872_reg_175 <= ap_phi_mux_last_2_3871_phi_fu_162_p8;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    last_2_3872_reg_175 <= ap_phi_reg_pp0_iter0_last_2_3872_reg_175;
                end if;
            end if; 
        end if;
    end process;

    last_8_reg_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    last_8_reg_146 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_516)) then 
                    last_8_reg_146 <= last_2_3872_reg_175;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_10_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_522)) then
                if ((ap_const_boolean_1 = ap_condition_541)) then 
                    p_Val2_10_fu_96 <= p_Result_10_fu_222_p4;
                elsif ((ap_const_boolean_1 = ap_condition_537)) then 
                    p_Val2_10_fu_96 <= p_Result_13_fu_251_p4;
                elsif ((ap_const_boolean_1 = ap_condition_532)) then 
                    p_Val2_10_fu_96 <= p_Result_16_fu_281_p4;
                elsif ((ap_const_boolean_1 = ap_condition_526)) then 
                    p_Val2_10_fu_96 <= p_Result_19_fu_355_p5;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_9_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_522)) then
                if ((ap_const_boolean_1 = ap_condition_541)) then 
                    p_Val2_9_fu_92 <= p_Result_11_fu_231_p4;
                elsif ((ap_const_boolean_1 = ap_condition_537)) then 
                    p_Val2_9_fu_92 <= p_Result_14_fu_260_p4;
                elsif ((ap_const_boolean_1 = ap_condition_532)) then 
                    p_Val2_9_fu_92 <= p_Result_17_fu_291_p4;
                elsif ((ap_const_boolean_1 = ap_condition_526)) then 
                    p_Val2_9_fu_92 <= p_Result_20_fu_364_p3;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_s_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_522)) then
                if ((ap_const_boolean_1 = ap_condition_541)) then 
                    p_Val2_s_fu_88 <= p_Result_9_fu_211_p5;
                elsif ((ap_const_boolean_1 = ap_condition_537)) then 
                    p_Val2_s_fu_88 <= p_Result_12_fu_240_p5;
                elsif ((ap_const_boolean_1 = ap_condition_532)) then 
                    p_Val2_s_fu_88 <= p_Result_15_fu_269_p5;
                elsif ((ap_const_boolean_1 = ap_condition_526)) then 
                    p_Val2_s_fu_88 <= p_Result_18_fu_346_p5;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                delayed_last_reg_135_pp0_iter1_reg <= delayed_last_reg_135;
                last_8_reg_146_pp0_iter1_reg <= last_8_reg_146;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                out_pixel_data_V_1_reg_533 <= p_Val2_s_fu_88(63 downto 32);
                out_pixel_data_V_2_reg_548 <= p_Val2_s_fu_88(95 downto 64);
                p_Result_5_reg_538 <= p_Val2_10_fu_96(1 downto 1);
                p_Result_6_reg_543 <= p_Val2_9_fu_92(2 downto 2);
                p_Result_7_reg_553 <= p_Val2_10_fu_96(2 downto 2);
                p_Result_8_reg_558 <= p_Val2_9_fu_92(3 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                tmp_data_V_10_reg_502 <= stream_in_24_TDATA;
                tmp_last_V_7_reg_514 <= stream_in_24_TLAST;
                tmp_user_V_9_reg_508 <= stream_in_24_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (tmp_last_V_7_reg_514 = ap_const_lv1_0) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                tmp_data_V_11_reg_519 <= stream_in_24_TDATA;
                tmp_last_V_8_reg_529 <= stream_in_24_TLAST;
                tmp_user_V_10_reg_524 <= stream_in_24_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_last_8_phi_fu_150_p4 = ap_const_lv1_0) and (ap_phi_mux_delayed_last_phi_fu_138_p4 = ap_const_lv1_0))) then
                tmp_data_V_reg_485 <= stream_in_24_TDATA;
                tmp_last_V_reg_497 <= stream_in_24_TLAST;
                tmp_user_V_reg_491 <= stream_in_24_TUSER;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter0_stage2, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, stream_out_32_TREADY, ap_predicate_op30_read_state1, ap_predicate_op90_write_state5)
    begin
                ap_block_pp0_stage0_01001 <= (((stream_out_32_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_predicate_op90_write_state5 = ap_const_boolean_1)) or ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op30_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, stream_out_32_TREADY, ap_predicate_op30_read_state1, ap_predicate_op90_write_state5, ap_block_state5_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((stream_out_32_TREADY = ap_const_logic_0) and (ap_predicate_op90_write_state5 = ap_const_boolean_1)))) or ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op30_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, stream_out_32_TREADY, ap_predicate_op30_read_state1, ap_predicate_op90_write_state5, ap_block_state5_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((stream_out_32_TREADY = ap_const_logic_0) and (ap_predicate_op90_write_state5 = ap_const_boolean_1)))) or ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op30_read_state1 = ap_const_boolean_1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, stream_out_32_TREADY, ap_predicate_op35_read_state2, ap_predicate_op97_write_state6)
    begin
                ap_block_pp0_stage1_01001 <= (((stream_out_32_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_predicate_op97_write_state6 = ap_const_boolean_1)) or ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op35_read_state2 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, stream_out_32_TREADY, ap_predicate_op35_read_state2, ap_predicate_op97_write_state6, ap_block_state6_io)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_out_32_TREADY = ap_const_logic_0) and (ap_predicate_op97_write_state6 = ap_const_boolean_1)))) or ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op35_read_state2 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, stream_out_32_TREADY, ap_predicate_op35_read_state2, ap_predicate_op97_write_state6, ap_block_state6_io)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_out_32_TREADY = ap_const_logic_0) and (ap_predicate_op97_write_state6 = ap_const_boolean_1)))) or ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op35_read_state2 = ap_const_boolean_1)));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, ap_predicate_op49_read_state3, stream_out_32_TREADY, ap_predicate_op98_write_state7)
    begin
                ap_block_pp0_stage2_01001 <= (((ap_predicate_op98_write_state7 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, ap_predicate_op49_read_state3, stream_out_32_TREADY, ap_predicate_op98_write_state7, ap_block_state7_io)
    begin
                ap_block_pp0_stage2_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state7_io) or ((ap_predicate_op98_write_state7 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0)))) or ((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, ap_predicate_op49_read_state3, stream_out_32_TREADY, ap_predicate_op98_write_state7, ap_block_state7_io)
    begin
                ap_block_pp0_stage2_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state7_io) or ((ap_predicate_op98_write_state7 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0)))) or ((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op69_read_state4)
    begin
                ap_block_pp0_stage3_11001 <= ((ap_predicate_op69_read_state4 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op69_read_state4)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_predicate_op69_read_state4 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(stream_in_24_TVALID, ap_predicate_op30_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((stream_in_24_TVALID = ap_const_logic_0) and (ap_predicate_op30_read_state1 = ap_const_boolean_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(stream_in_24_TVALID, ap_predicate_op35_read_state2)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((stream_in_24_TVALID = ap_const_logic_0) and (ap_predicate_op35_read_state2 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(stream_in_24_TVALID, ap_predicate_op49_read_state3)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(stream_in_24_TVALID, ap_predicate_op69_read_state4)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((ap_predicate_op69_read_state4 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0));
    end process;


    ap_block_state5_io_assign_proc : process(stream_out_32_TREADY, ap_predicate_op90_write_state5)
    begin
                ap_block_state5_io <= ((stream_out_32_TREADY = ap_const_logic_0) and (ap_predicate_op90_write_state5 = ap_const_boolean_1));
    end process;


    ap_block_state5_pp0_stage0_iter1_assign_proc : process(stream_out_32_TREADY, ap_predicate_op90_write_state5)
    begin
                ap_block_state5_pp0_stage0_iter1 <= ((stream_out_32_TREADY = ap_const_logic_0) and (ap_predicate_op90_write_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_io_assign_proc : process(stream_out_32_TREADY, ap_predicate_op97_write_state6)
    begin
                ap_block_state6_io <= ((stream_out_32_TREADY = ap_const_logic_0) and (ap_predicate_op97_write_state6 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage1_iter1_assign_proc : process(stream_out_32_TREADY, ap_predicate_op97_write_state6)
    begin
                ap_block_state6_pp0_stage1_iter1 <= ((stream_out_32_TREADY = ap_const_logic_0) and (ap_predicate_op97_write_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_io_assign_proc : process(stream_out_32_TREADY, ap_predicate_op98_write_state7)
    begin
                ap_block_state7_io <= ((ap_predicate_op98_write_state7 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0));
    end process;


    ap_block_state7_pp0_stage2_iter1_assign_proc : process(stream_out_32_TREADY, ap_predicate_op98_write_state7)
    begin
                ap_block_state7_pp0_stage2_iter1 <= ((ap_predicate_op98_write_state7 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0));
    end process;


    ap_condition_262_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
                ap_condition_262 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_512_assign_proc : process(ap_enable_reg_pp0_iter1, delayed_last_reg_135, ap_block_pp0_stage0)
    begin
                ap_condition_512 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (delayed_last_reg_135 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_516_assign_proc : process(ap_enable_reg_pp0_iter1, delayed_last_reg_135, ap_block_pp0_stage0_11001)
    begin
                ap_condition_516 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (delayed_last_reg_135 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_522_assign_proc : process(ap_enable_reg_pp0_iter0, delayed_last_reg_135, last_8_reg_146)
    begin
                ap_condition_522 <= ((last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_526_assign_proc : process(tmp_last_V_reg_497, tmp_last_V_7_reg_514, ap_CS_fsm_pp0_stage3, tmp_last_V_8_reg_529, ap_block_pp0_stage3_11001)
    begin
                ap_condition_526 <= ((tmp_last_V_8_reg_529 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (tmp_last_V_7_reg_514 = ap_const_lv1_0) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_532_assign_proc : process(ap_CS_fsm_pp0_stage2, tmp_last_V_reg_497, tmp_last_V_7_reg_514, grp_fu_197_p1, ap_block_pp0_stage2_11001)
    begin
                ap_condition_532 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (tmp_last_V_7_reg_514 = ap_const_lv1_0) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (grp_fu_197_p1 = ap_const_lv1_1));
    end process;


    ap_condition_537_assign_proc : process(ap_CS_fsm_pp0_stage2, tmp_last_V_reg_497, tmp_last_V_7_reg_514, ap_block_pp0_stage2_11001)
    begin
                ap_condition_537 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (tmp_last_V_7_reg_514 = ap_const_lv1_1) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_541_assign_proc : process(ap_CS_fsm_pp0_stage2, tmp_last_V_reg_497, ap_block_pp0_stage2_11001)
    begin
                ap_condition_541 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (tmp_last_V_reg_497 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_547_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op90_write_state5, ap_block_pp0_stage0_01001)
    begin
                ap_condition_547 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op90_write_state5 = ap_const_boolean_1));
    end process;


    ap_condition_551_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_predicate_op97_write_state6, ap_block_pp0_stage1_01001)
    begin
                ap_condition_551 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_predicate_op97_write_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_condition_555_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_predicate_op98_write_state7, ap_block_pp0_stage2_01001)
    begin
                ap_condition_555 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_predicate_op98_write_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, delayed_last_reg_135, ap_block_pp0_stage2_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (delayed_last_reg_135 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;

    ap_phi_mux_delayed_last_phi_fu_138_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, last_8_reg_146, ap_loop_init, ap_condition_512)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_delayed_last_phi_fu_138_p4 <= ap_const_lv1_0;
            elsif ((ap_const_boolean_1 = ap_condition_512)) then 
                ap_phi_mux_delayed_last_phi_fu_138_p4 <= last_8_reg_146;
            else 
                ap_phi_mux_delayed_last_phi_fu_138_p4 <= ap_const_lv1_0;
            end if;
        else 
            ap_phi_mux_delayed_last_phi_fu_138_p4 <= ap_const_lv1_0;
        end if; 
    end process;


    ap_phi_mux_last_2_3871_phi_fu_162_p8_assign_proc : process(delayed_last_reg_135, last_8_reg_146, tmp_last_V_reg_497, tmp_last_V_7_reg_514, tmp_last_V_8_reg_529, stream_in_24_TLAST)
    begin
        if (((tmp_last_V_8_reg_529 = ap_const_lv1_0) and (tmp_last_V_7_reg_514 = ap_const_lv1_0) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0))) then 
            ap_phi_mux_last_2_3871_phi_fu_162_p8 <= stream_in_24_TLAST;
        else 
            ap_phi_mux_last_2_3871_phi_fu_162_p8 <= ap_const_lv1_1;
        end if; 
    end process;


    ap_phi_mux_last_8_phi_fu_150_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, last_2_3872_reg_175, ap_loop_init, ap_condition_512)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_last_8_phi_fu_150_p4 <= ap_const_lv1_0;
            elsif ((ap_const_boolean_1 = ap_condition_512)) then 
                ap_phi_mux_last_8_phi_fu_150_p4 <= last_2_3872_reg_175;
            else 
                ap_phi_mux_last_8_phi_fu_150_p4 <= ap_const_lv1_0;
            end if;
        else 
            ap_phi_mux_last_8_phi_fu_150_p4 <= ap_const_lv1_0;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_last_2_3872_reg_175 <= ap_const_lv1_1;

    ap_predicate_op30_read_state1_assign_proc : process(ap_phi_mux_delayed_last_phi_fu_138_p4, ap_phi_mux_last_8_phi_fu_150_p4)
    begin
                ap_predicate_op30_read_state1 <= ((ap_phi_mux_last_8_phi_fu_150_p4 = ap_const_lv1_0) and (ap_phi_mux_delayed_last_phi_fu_138_p4 = ap_const_lv1_0));
    end process;


    ap_predicate_op35_read_state2_assign_proc : process(delayed_last_reg_135, last_8_reg_146, tmp_last_V_reg_497)
    begin
                ap_predicate_op35_read_state2 <= ((tmp_last_V_reg_497 = ap_const_lv1_0) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0));
    end process;


    ap_predicate_op49_read_state3_assign_proc : process(delayed_last_reg_135, last_8_reg_146, tmp_last_V_reg_497, tmp_last_V_7_reg_514)
    begin
                ap_predicate_op49_read_state3 <= ((tmp_last_V_7_reg_514 = ap_const_lv1_0) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0));
    end process;


    ap_predicate_op69_read_state4_assign_proc : process(delayed_last_reg_135, last_8_reg_146, tmp_last_V_reg_497, tmp_last_V_7_reg_514, tmp_last_V_8_reg_529)
    begin
                ap_predicate_op69_read_state4 <= ((tmp_last_V_8_reg_529 = ap_const_lv1_0) and (tmp_last_V_7_reg_514 = ap_const_lv1_0) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0));
    end process;


    ap_predicate_op90_write_state5_assign_proc : process(delayed_last_reg_135, last_8_reg_146)
    begin
                ap_predicate_op90_write_state5 <= ((last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0));
    end process;


    ap_predicate_op97_write_state6_assign_proc : process(delayed_last_reg_135_pp0_iter1_reg, last_8_reg_146_pp0_iter1_reg)
    begin
                ap_predicate_op97_write_state6 <= ((last_8_reg_146_pp0_iter1_reg = ap_const_lv1_0) and (delayed_last_reg_135_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op98_write_state7_assign_proc : process(delayed_last_reg_135_pp0_iter1_reg, last_8_reg_146_pp0_iter1_reg)
    begin
                ap_predicate_op98_write_state7 <= ((last_8_reg_146_pp0_iter1_reg = ap_const_lv1_0) and (delayed_last_reg_135_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_197_p1 <= stream_in_24_TLAST;
    out_pixel_data_V_fu_392_p1 <= p_Val2_s_fu_88(32 - 1 downto 0);
    
    p_Result_10_fu_222_p4_proc : process(p_Val2_10_fu_96, tmp_user_V_reg_491)
    begin
        p_Result_10_fu_222_p4 <= p_Val2_10_fu_96;
        p_Result_10_fu_222_p4(0) <= tmp_user_V_reg_491(0);
    end process;

    
    p_Result_11_fu_231_p4_proc : process(p_Val2_9_fu_92, tmp_last_V_reg_497)
    begin
        p_Result_11_fu_231_p4 <= p_Val2_9_fu_92;
        p_Result_11_fu_231_p4(0) <= tmp_last_V_reg_497(0);
    end process;

    p_Result_12_fu_240_p5 <= (p_Result_9_fu_211_p5(95 downto 48) & tmp_data_V_10_reg_502 & p_Result_9_fu_211_p5(23 downto 0));
    
    p_Result_13_fu_251_p4_proc : process(p_Result_10_fu_222_p4, tmp_user_V_9_reg_508)
    begin
        p_Result_13_fu_251_p4 <= p_Result_10_fu_222_p4;
        p_Result_13_fu_251_p4(1) <= tmp_user_V_9_reg_508(0);
    end process;

    
    p_Result_14_fu_260_p4_proc : process(p_Result_11_fu_231_p4, tmp_last_V_7_reg_514)
    begin
        p_Result_14_fu_260_p4 <= p_Result_11_fu_231_p4;
        p_Result_14_fu_260_p4(1) <= tmp_last_V_7_reg_514(0);
    end process;

    p_Result_15_fu_269_p5 <= (p_Result_12_fu_240_p5(95 downto 72) & stream_in_24_TDATA & p_Result_12_fu_240_p5(47 downto 0));
    
    p_Result_16_fu_281_p4_proc : process(p_Result_13_fu_251_p4, stream_in_24_TUSER)
    begin
        p_Result_16_fu_281_p4 <= p_Result_13_fu_251_p4;
        p_Result_16_fu_281_p4(2) <= stream_in_24_TUSER(0);
    end process;

    
    p_Result_17_fu_291_p4_proc : process(p_Result_14_fu_260_p4, stream_in_24_TLAST)
    begin
        p_Result_17_fu_291_p4 <= p_Result_14_fu_260_p4;
        p_Result_17_fu_291_p4(2) <= stream_in_24_TLAST(0);
    end process;

    p_Result_18_fu_346_p5 <= (((stream_in_24_TDATA & tmp_data_V_11_reg_519) & tmp_data_V_10_reg_502) & tmp_data_V_reg_485);
    p_Result_19_fu_355_p5 <= (((stream_in_24_TUSER & tmp_user_V_10_reg_524) & tmp_user_V_9_reg_508) & tmp_user_V_reg_491);
    p_Result_20_fu_364_p3 <= (stream_in_24_TLAST & ap_const_lv3_0);
    p_Result_9_fu_211_p5 <= (p_Val2_s_fu_88(95 downto 24) & tmp_data_V_reg_485);
    p_Result_s_fu_387_p1 <= p_Val2_10_fu_96(1 - 1 downto 0);

    stream_in_24_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, stream_in_24_TVALID, delayed_last_reg_135, last_8_reg_146, tmp_last_V_reg_497, ap_predicate_op49_read_state3, ap_CS_fsm_pp0_stage3, ap_predicate_op69_read_state4, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_phi_mux_delayed_last_phi_fu_138_p4, ap_phi_mux_last_8_phi_fu_150_p4, ap_block_pp0_stage3)
    begin
        if ((((ap_predicate_op69_read_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_predicate_op49_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (tmp_last_V_reg_497 = ap_const_lv1_0) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_last_8_phi_fu_150_p4 = ap_const_lv1_0) and (ap_phi_mux_delayed_last_phi_fu_138_p4 = ap_const_lv1_0)))) then 
            stream_in_24_TDATA_blk_n <= stream_in_24_TVALID;
        else 
            stream_in_24_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_24_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_predicate_op49_read_state3, ap_CS_fsm_pp0_stage3, ap_predicate_op69_read_state4, ap_CS_fsm_pp0_stage1, ap_predicate_op30_read_state1, ap_block_pp0_stage0_11001, ap_predicate_op35_read_state2, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_predicate_op69_read_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_predicate_op49_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op35_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op30_read_state1 = ap_const_boolean_1)))) then 
            stream_in_24_TREADY <= ap_const_logic_1;
        else 
            stream_in_24_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_out_32_TDATA_assign_proc : process(ap_enable_reg_pp0_iter1, out_pixel_data_V_1_reg_533, out_pixel_data_V_2_reg_548, out_pixel_data_V_fu_392_p1, ap_condition_547, ap_condition_551, ap_condition_555)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_555)) then 
                stream_out_32_TDATA <= out_pixel_data_V_2_reg_548;
            elsif ((ap_const_boolean_1 = ap_condition_551)) then 
                stream_out_32_TDATA <= out_pixel_data_V_1_reg_533;
            elsif ((ap_const_boolean_1 = ap_condition_547)) then 
                stream_out_32_TDATA <= out_pixel_data_V_fu_392_p1;
            else 
                stream_out_32_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            stream_out_32_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stream_out_32_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, delayed_last_reg_135, last_8_reg_146, stream_out_32_TREADY, delayed_last_reg_135_pp0_iter1_reg, last_8_reg_146_pp0_iter1_reg, ap_predicate_op98_write_state7, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_predicate_op98_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (last_8_reg_146_pp0_iter1_reg = ap_const_lv1_0) and (delayed_last_reg_135_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (last_8_reg_146 = ap_const_lv1_0) and (delayed_last_reg_135 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            stream_out_32_TDATA_blk_n <= stream_out_32_TREADY;
        else 
            stream_out_32_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_out_32_TKEEP <= ap_const_lv4_0;

    stream_out_32_TLAST_assign_proc : process(ap_enable_reg_pp0_iter1, p_Result_6_reg_543, p_Result_8_reg_558, p_Val2_9_fu_92, ap_condition_547, ap_condition_551, ap_condition_555)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_555)) then 
                stream_out_32_TLAST <= p_Result_8_reg_558;
            elsif ((ap_const_boolean_1 = ap_condition_551)) then 
                stream_out_32_TLAST <= p_Result_6_reg_543;
            elsif ((ap_const_boolean_1 = ap_condition_547)) then 
                stream_out_32_TLAST <= p_Val2_9_fu_92(1 downto 1);
            else 
                stream_out_32_TLAST <= "X";
            end if;
        else 
            stream_out_32_TLAST <= "X";
        end if; 
    end process;

    stream_out_32_TSTRB <= ap_const_lv4_0;

    stream_out_32_TUSER_assign_proc : process(ap_enable_reg_pp0_iter1, p_Result_5_reg_538, p_Result_7_reg_553, p_Result_s_fu_387_p1, ap_condition_547, ap_condition_551, ap_condition_555)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_555)) then 
                stream_out_32_TUSER <= p_Result_7_reg_553;
            elsif ((ap_const_boolean_1 = ap_condition_551)) then 
                stream_out_32_TUSER <= p_Result_5_reg_538;
            elsif ((ap_const_boolean_1 = ap_condition_547)) then 
                stream_out_32_TUSER <= p_Result_s_fu_387_p1;
            else 
                stream_out_32_TUSER <= "X";
            end if;
        else 
            stream_out_32_TUSER <= "X";
        end if; 
    end process;


    stream_out_32_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_predicate_op98_write_state7, ap_CS_fsm_pp0_stage1, ap_predicate_op90_write_state5, ap_block_pp0_stage0_11001, ap_predicate_op97_write_state6, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_predicate_op98_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_predicate_op97_write_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op90_write_state5 = ap_const_boolean_1)))) then 
            stream_out_32_TVALID <= ap_const_logic_1;
        else 
            stream_out_32_TVALID <= ap_const_logic_0;
        end if; 
    end process;

end behav;
