-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_62_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_in_24_TVALID : IN STD_LOGIC;
    stream_out_32_TREADY : IN STD_LOGIC;
    stream_out_32_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_out_32_TVALID : OUT STD_LOGIC;
    stream_out_32_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_32_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_32_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_32_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_in_24_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_in_24_TREADY : OUT STD_LOGIC;
    stream_in_24_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_24_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_in_24_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_24_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_62_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_phi_mux_delayed_last_phi_fu_108_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_last_4_phi_fu_120_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op26_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal delayed_last_reg_105 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_4_reg_116 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op71_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal tmp_last_V_1_reg_313 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_2_reg_323 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_3_reg_339 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op56_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal stream_out_32_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal stream_in_24_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal tmp_last_V_reg_128 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_6_3885_reg_147 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_user_V_3_reg_307 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_fu_179_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln674_fu_192_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln674_reg_317 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op32_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal user_2_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal user_2_reg_327 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln674_1_fu_205_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln674_1_reg_333 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op42_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal user_3_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal user_3_reg_343 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln674_2_fu_240_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln674_2_reg_349 : STD_LOGIC_VECTOR (7 downto 0);
    signal user_4_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_loop_init : STD_LOGIC;
    signal ap_phi_mux_tmp_last_V_phi_fu_133_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_last_V_reg_128 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_last_6_3885_reg_147 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_user_V_reg_161 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_user_V_reg_161 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_fu_66 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_3_fu_284_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_2_fu_244_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_1_fu_220_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_209_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln674_3_fu_280_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_414 : BOOLEAN;
    signal ap_condition_423 : BOOLEAN;
    signal ap_condition_420 : BOOLEAN;
    signal ap_condition_88 : BOOLEAN;
    signal ap_condition_226 : BOOLEAN;
    signal ap_condition_436 : BOOLEAN;
    signal ap_condition_441 : BOOLEAN;
    signal ap_condition_446 : BOOLEAN;
    signal ap_condition_450 : BOOLEAN;
    signal ap_condition_454 : BOOLEAN;
    signal ap_condition_418 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component pixel_pack_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pixel_pack_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter0_tmp_user_V_reg_161_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_420)) then
                if ((ap_const_boolean_1 = ap_condition_423)) then 
                    ap_phi_reg_pp0_iter0_tmp_user_V_reg_161 <= user_3_fu_235_p2;
                elsif (((tmp_last_V_2_reg_323 = ap_const_lv1_1) and (tmp_last_V_1_reg_313 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter0_tmp_user_V_reg_161 <= user_2_reg_327;
                elsif ((tmp_last_V_1_reg_313 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_tmp_user_V_reg_161 <= tmp_user_V_3_reg_307;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_tmp_user_V_reg_161_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_226)) then
                if ((ap_const_boolean_1 = ap_condition_88)) then 
                    ap_phi_reg_pp0_iter1_tmp_user_V_reg_161 <= user_4_fu_275_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_tmp_user_V_reg_161 <= ap_phi_reg_pp0_iter0_tmp_user_V_reg_161;
                end if;
            end if; 
        end if;
    end process;

    delayed_last_reg_105_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    delayed_last_reg_105 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_436)) then 
                    delayed_last_reg_105 <= last_4_reg_116;
                end if;
            end if; 
        end if;
    end process;

    last_4_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    last_4_reg_116 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_436)) then 
                    last_4_reg_116 <= last_6_3885_reg_147;
                end if;
            end if; 
        end if;
    end process;

    last_6_3885_reg_147_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_226)) then
                if (((last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0))) then 
                    last_6_3885_reg_147 <= ap_phi_mux_tmp_last_V_phi_fu_133_p8;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    last_6_3885_reg_147 <= ap_phi_reg_pp0_iter0_last_6_3885_reg_147;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_s_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_418)) then
                if ((ap_const_boolean_1 = ap_condition_454)) then 
                    p_Val2_s_fu_66 <= p_Result_s_fu_209_p5;
                elsif ((ap_const_boolean_1 = ap_condition_450)) then 
                    p_Val2_s_fu_66 <= p_Result_1_fu_220_p5;
                elsif ((ap_const_boolean_1 = ap_condition_446)) then 
                    p_Val2_s_fu_66 <= p_Result_2_fu_244_p5;
                elsif ((ap_const_boolean_1 = ap_condition_441)) then 
                    p_Val2_s_fu_66 <= p_Result_3_fu_284_p5;
                end if;
            end if; 
        end if;
    end process;

    tmp_last_V_reg_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_226)) then
                if ((ap_const_boolean_1 = ap_condition_88)) then 
                    tmp_last_V_reg_128 <= stream_in_24_TLAST;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    tmp_last_V_reg_128 <= ap_phi_reg_pp0_iter0_tmp_last_V_reg_128;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_phi_mux_last_4_phi_fu_120_p4 = ap_const_lv1_0) and (ap_phi_mux_delayed_last_phi_fu_108_p4 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_last_V_1_reg_313 <= stream_in_24_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                tmp_last_V_2_reg_323 <= stream_in_24_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                tmp_last_V_3_reg_339 <= stream_in_24_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_phi_mux_last_4_phi_fu_120_p4 = ap_const_lv1_0) and (ap_phi_mux_delayed_last_phi_fu_108_p4 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_user_V_3_reg_307 <= stream_in_24_TUSER;
                trunc_ln674_reg_317 <= trunc_ln674_fu_192_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                trunc_ln674_1_reg_333 <= trunc_ln674_1_fu_205_p1;
                user_2_reg_327 <= user_2_fu_200_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                trunc_ln674_2_reg_349 <= trunc_ln674_2_fu_240_p1;
                user_3_reg_343 <= user_3_fu_235_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage3_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, ap_predicate_op26_read_state1, stream_out_32_TREADY, ap_predicate_op71_write_state5)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_predicate_op71_write_state5 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_predicate_op26_read_state1 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, ap_predicate_op26_read_state1, stream_out_32_TREADY, ap_predicate_op71_write_state5, ap_block_state5_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((ap_predicate_op71_write_state5 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0)))) or ((ap_predicate_op26_read_state1 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, stream_in_24_TVALID, ap_predicate_op26_read_state1, stream_out_32_TREADY, ap_predicate_op71_write_state5, ap_block_state5_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((ap_predicate_op71_write_state5 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0)))) or ((ap_predicate_op26_read_state1 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op32_read_state2)
    begin
                ap_block_pp0_stage1_11001 <= ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op32_read_state2 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op32_read_state2)
    begin
                ap_block_pp0_stage1_subdone <= ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op32_read_state2 = ap_const_boolean_1));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op42_read_state3)
    begin
                ap_block_pp0_stage2_11001 <= ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op42_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op42_read_state3)
    begin
                ap_block_pp0_stage2_subdone <= ((stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op42_read_state3 = ap_const_boolean_1));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op56_read_state4)
    begin
                ap_block_pp0_stage3_11001 <= ((ap_predicate_op56_read_state4 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op56_read_state4)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_predicate_op56_read_state4 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(stream_in_24_TVALID, ap_predicate_op26_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_predicate_op26_read_state1 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(stream_in_24_TVALID, ap_predicate_op32_read_state2)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((stream_in_24_TVALID = ap_const_logic_0) and (ap_predicate_op32_read_state2 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(stream_in_24_TVALID, ap_predicate_op42_read_state3)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((stream_in_24_TVALID = ap_const_logic_0) and (ap_predicate_op42_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(stream_in_24_TVALID, ap_predicate_op56_read_state4)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((ap_predicate_op56_read_state4 = ap_const_boolean_1) and (stream_in_24_TVALID = ap_const_logic_0));
    end process;


    ap_block_state5_io_assign_proc : process(stream_out_32_TREADY, ap_predicate_op71_write_state5)
    begin
                ap_block_state5_io <= ((ap_predicate_op71_write_state5 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter1_assign_proc : process(stream_out_32_TREADY, ap_predicate_op71_write_state5)
    begin
                ap_block_state5_pp0_stage0_iter1 <= ((ap_predicate_op71_write_state5 = ap_const_boolean_1) and (stream_out_32_TREADY = ap_const_logic_0));
    end process;


    ap_condition_226_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
                ap_condition_226 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_414_assign_proc : process(ap_enable_reg_pp0_iter1, delayed_last_reg_105, ap_block_pp0_stage0)
    begin
                ap_condition_414 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_418_assign_proc : process(ap_enable_reg_pp0_iter0, delayed_last_reg_105, last_4_reg_116)
    begin
                ap_condition_418 <= ((last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_420_assign_proc : process(ap_enable_reg_pp0_iter0, delayed_last_reg_105, last_4_reg_116, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
                ap_condition_420 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_423_assign_proc : process(tmp_last_V_1_reg_313, tmp_last_V_2_reg_323, grp_fu_179_p1)
    begin
                ap_condition_423 <= ((tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (grp_fu_179_p1 = ap_const_lv1_1));
    end process;


    ap_condition_436_assign_proc : process(ap_enable_reg_pp0_iter1, delayed_last_reg_105, ap_block_pp0_stage0_11001)
    begin
                ap_condition_436 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_441_assign_proc : process(ap_CS_fsm_pp0_stage3, tmp_last_V_1_reg_313, tmp_last_V_2_reg_323, tmp_last_V_3_reg_339, ap_block_pp0_stage3_11001)
    begin
                ap_condition_441 <= ((tmp_last_V_3_reg_339 = ap_const_lv1_0) and (tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_446_assign_proc : process(tmp_last_V_1_reg_313, tmp_last_V_2_reg_323, ap_CS_fsm_pp0_stage2, grp_fu_179_p1, ap_block_pp0_stage2_11001)
    begin
                ap_condition_446 <= ((tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (grp_fu_179_p1 = ap_const_lv1_1));
    end process;


    ap_condition_450_assign_proc : process(tmp_last_V_1_reg_313, tmp_last_V_2_reg_323, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
                ap_condition_450 <= ((tmp_last_V_2_reg_323 = ap_const_lv1_1) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_454_assign_proc : process(tmp_last_V_1_reg_313, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
                ap_condition_454 <= ((tmp_last_V_1_reg_313 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_88_assign_proc : process(delayed_last_reg_105, last_4_reg_116, tmp_last_V_1_reg_313, tmp_last_V_2_reg_323, tmp_last_V_3_reg_339)
    begin
                ap_condition_88 <= ((tmp_last_V_3_reg_339 = ap_const_lv1_0) and (tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_phi_mux_delayed_last_phi_fu_108_p4, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_phi_mux_delayed_last_phi_fu_108_p4 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_delayed_last_phi_fu_108_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, last_4_reg_116, ap_loop_init, ap_condition_414)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_delayed_last_phi_fu_108_p4 <= ap_const_lv1_0;
            elsif ((ap_const_boolean_1 = ap_condition_414)) then 
                ap_phi_mux_delayed_last_phi_fu_108_p4 <= last_4_reg_116;
            else 
                ap_phi_mux_delayed_last_phi_fu_108_p4 <= ap_const_lv1_0;
            end if;
        else 
            ap_phi_mux_delayed_last_phi_fu_108_p4 <= ap_const_lv1_0;
        end if; 
    end process;


    ap_phi_mux_last_4_phi_fu_120_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, last_6_3885_reg_147, ap_loop_init, ap_condition_414)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_last_4_phi_fu_120_p4 <= ap_const_lv1_0;
            elsif ((ap_const_boolean_1 = ap_condition_414)) then 
                ap_phi_mux_last_4_phi_fu_120_p4 <= last_6_3885_reg_147;
            else 
                ap_phi_mux_last_4_phi_fu_120_p4 <= ap_const_lv1_0;
            end if;
        else 
            ap_phi_mux_last_4_phi_fu_120_p4 <= ap_const_lv1_0;
        end if; 
    end process;


    ap_phi_mux_tmp_last_V_phi_fu_133_p8_assign_proc : process(delayed_last_reg_105, last_4_reg_116, tmp_last_V_1_reg_313, tmp_last_V_2_reg_323, tmp_last_V_3_reg_339, stream_in_24_TLAST)
    begin
        if (((tmp_last_V_3_reg_339 = ap_const_lv1_0) and (tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0))) then 
            ap_phi_mux_tmp_last_V_phi_fu_133_p8 <= stream_in_24_TLAST;
        else 
            ap_phi_mux_tmp_last_V_phi_fu_133_p8 <= ap_const_lv1_1;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_last_6_3885_reg_147 <= ap_const_lv1_1;
    ap_phi_reg_pp0_iter0_tmp_last_V_reg_128 <= ap_const_lv1_1;

    ap_predicate_op26_read_state1_assign_proc : process(ap_phi_mux_delayed_last_phi_fu_108_p4, ap_phi_mux_last_4_phi_fu_120_p4)
    begin
                ap_predicate_op26_read_state1 <= ((ap_phi_mux_last_4_phi_fu_120_p4 = ap_const_lv1_0) and (ap_phi_mux_delayed_last_phi_fu_108_p4 = ap_const_lv1_0));
    end process;


    ap_predicate_op32_read_state2_assign_proc : process(delayed_last_reg_105, last_4_reg_116, tmp_last_V_1_reg_313)
    begin
                ap_predicate_op32_read_state2 <= ((tmp_last_V_1_reg_313 = ap_const_lv1_0) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0));
    end process;


    ap_predicate_op42_read_state3_assign_proc : process(delayed_last_reg_105, last_4_reg_116, tmp_last_V_1_reg_313, tmp_last_V_2_reg_323)
    begin
                ap_predicate_op42_read_state3 <= ((tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0));
    end process;


    ap_predicate_op56_read_state4_assign_proc : process(delayed_last_reg_105, last_4_reg_116, tmp_last_V_1_reg_313, tmp_last_V_2_reg_323, tmp_last_V_3_reg_339)
    begin
                ap_predicate_op56_read_state4 <= ((tmp_last_V_3_reg_339 = ap_const_lv1_0) and (tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0));
    end process;


    ap_predicate_op71_write_state5_assign_proc : process(delayed_last_reg_105, last_4_reg_116)
    begin
                ap_predicate_op71_write_state5 <= ((last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_179_p1 <= stream_in_24_TLAST;
    p_Result_1_fu_220_p5 <= (p_Result_s_fu_209_p5(31 downto 16) & trunc_ln674_1_reg_333 & p_Result_s_fu_209_p5(7 downto 0));
    p_Result_2_fu_244_p5 <= (p_Result_1_fu_220_p5(31 downto 24) & trunc_ln674_2_fu_240_p1 & p_Result_1_fu_220_p5(15 downto 0));
    p_Result_3_fu_284_p5 <= (((trunc_ln674_3_fu_280_p1 & trunc_ln674_2_reg_349) & trunc_ln674_1_reg_333) & trunc_ln674_reg_317);
    p_Result_s_fu_209_p5 <= (p_Val2_s_fu_66(31 downto 8) & trunc_ln674_reg_317);

    stream_in_24_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, stream_in_24_TVALID, ap_predicate_op26_read_state1, delayed_last_reg_105, last_4_reg_116, ap_CS_fsm_pp0_stage3, tmp_last_V_1_reg_313, tmp_last_V_2_reg_323, ap_predicate_op56_read_state4, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if ((((ap_predicate_op56_read_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((tmp_last_V_2_reg_323 = ap_const_lv1_0) and (tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((tmp_last_V_1_reg_313 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (last_4_reg_116 = ap_const_lv1_0) and (delayed_last_reg_105 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op26_read_state1 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            stream_in_24_TDATA_blk_n <= stream_in_24_TVALID;
        else 
            stream_in_24_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_24_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_predicate_op26_read_state1, ap_CS_fsm_pp0_stage3, ap_predicate_op56_read_state4, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001, ap_predicate_op32_read_state2, ap_block_pp0_stage1_11001, ap_predicate_op42_read_state3, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_predicate_op56_read_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_predicate_op42_read_state3 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_op32_read_state2 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op26_read_state1 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            stream_in_24_TREADY <= ap_const_logic_1;
        else 
            stream_in_24_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    stream_out_32_TDATA <= p_Val2_s_fu_66;

    stream_out_32_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_out_32_TREADY, ap_predicate_op71_write_state5, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op71_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_out_32_TDATA_blk_n <= stream_out_32_TREADY;
        else 
            stream_out_32_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_out_32_TKEEP <= ap_const_lv4_0;
    stream_out_32_TLAST <= tmp_last_V_reg_128;
    stream_out_32_TSTRB <= ap_const_lv4_0;
    stream_out_32_TUSER <= ap_phi_reg_pp0_iter1_tmp_user_V_reg_161;

    stream_out_32_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op71_write_state5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op71_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_out_32_TVALID <= ap_const_logic_1;
        else 
            stream_out_32_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln674_1_fu_205_p1 <= stream_in_24_TDATA(8 - 1 downto 0);
    trunc_ln674_2_fu_240_p1 <= stream_in_24_TDATA(8 - 1 downto 0);
    trunc_ln674_3_fu_280_p1 <= stream_in_24_TDATA(8 - 1 downto 0);
    trunc_ln674_fu_192_p1 <= stream_in_24_TDATA(8 - 1 downto 0);
    user_2_fu_200_p2 <= (tmp_user_V_3_reg_307 or stream_in_24_TUSER);
    user_3_fu_235_p2 <= (user_2_reg_327 or stream_in_24_TUSER);
    user_4_fu_275_p2 <= (user_3_reg_343 or stream_in_24_TUSER);
end behav;
