-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pixel_unpack is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_local_block : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    stream_in_32_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_32_TVALID : IN STD_LOGIC;
    stream_in_32_TREADY : OUT STD_LOGIC;
    stream_in_32_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_32_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_32_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_32_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_24_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_out_24_TVALID : OUT STD_LOGIC;
    stream_out_24_TREADY : IN STD_LOGIC;
    stream_out_24_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_out_24_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    stream_out_24_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_out_24_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of pixel_unpack is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pixel_unpack_pixel_unpack,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.302000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=337,HLS_SYN_LUT=808,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_local_deadlock : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_n_inv : STD_LOGIC;
    signal mode : STD_LOGIC_VECTOR (31 downto 0);
    signal mode_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal mode_0_vld_reg : STD_LOGIC := '0';
    signal mode_0_ack_out : STD_LOGIC;
    signal grp_read_fu_74_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mode_read_reg_200 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_done : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_idle : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_ready : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_in_32_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_done : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_idle : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_ready : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_in_32_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_done : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_idle : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_ready : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_in_32_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_done : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_idle : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_ready : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_in_32_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_done : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_idle : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_ready : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_in_32_TREADY : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID : STD_LOGIC;
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start_reg : STD_LOGIC := '0';
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start_reg : STD_LOGIC := '0';
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start_reg : STD_LOGIC := '0';
    signal grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_stream_out_24_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_stream_in_32_V_data_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_32_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal stream_in_32_TVALID_int_regslice : STD_LOGIC;
    signal stream_in_32_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_in_32_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_32_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_32_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_stream_in_32_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_32_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_32_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_32_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_stream_in_32_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_32_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_32_V_user_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_32_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_32_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_32_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_stream_in_32_V_last_V_U_apdone_blk : STD_LOGIC;
    signal stream_in_32_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_in_32_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_in_32_V_last_V_U_ack_in : STD_LOGIC;
    signal stream_out_24_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal stream_out_24_TVALID_int_regslice : STD_LOGIC;
    signal stream_out_24_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_out_24_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_24_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal stream_out_24_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_stream_out_24_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_24_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_24_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal stream_out_24_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_stream_out_24_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_24_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_24_V_user_V_U_apdone_blk : STD_LOGIC;
    signal stream_out_24_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_out_24_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_24_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_24_V_last_V_U_apdone_blk : STD_LOGIC;
    signal stream_out_24_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_stream_out_24_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_24_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_85_9 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_out_24_TREADY : IN STD_LOGIC;
        stream_in_32_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_in_32_TVALID : IN STD_LOGIC;
        stream_in_32_TREADY : OUT STD_LOGIC;
        stream_in_32_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_32_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_out_24_TVALID : OUT STD_LOGIC;
        stream_out_24_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_68_7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_out_24_TREADY : IN STD_LOGIC;
        stream_in_32_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_in_32_TVALID : IN STD_LOGIC;
        stream_in_32_TREADY : OUT STD_LOGIC;
        stream_in_32_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_32_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_out_24_TVALID : OUT STD_LOGIC;
        stream_out_24_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_51_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_out_24_TREADY : IN STD_LOGIC;
        stream_in_32_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_in_32_TVALID : IN STD_LOGIC;
        stream_in_32_TREADY : OUT STD_LOGIC;
        stream_in_32_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_32_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_out_24_TVALID : OUT STD_LOGIC;
        stream_out_24_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_40_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_32_TVALID : IN STD_LOGIC;
        stream_out_24_TREADY : IN STD_LOGIC;
        stream_in_32_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_in_32_TREADY : OUT STD_LOGIC;
        stream_in_32_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_32_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_out_24_TVALID : OUT STD_LOGIC;
        stream_out_24_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_19_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_out_24_TREADY : IN STD_LOGIC;
        stream_in_32_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_in_32_TVALID : IN STD_LOGIC;
        stream_in_32_TREADY : OUT STD_LOGIC;
        stream_in_32_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_32_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in_32_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_out_24_TVALID : OUT STD_LOGIC;
        stream_out_24_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        stream_out_24_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        stream_out_24_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component pixel_unpack_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        mode : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_local_deadlock : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component pixel_unpack_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80 : component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_85_9
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start,
        ap_done => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_done,
        ap_idle => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_idle,
        ap_ready => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_ready,
        stream_out_24_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TREADY,
        stream_in_32_TDATA => stream_in_32_TDATA_int_regslice,
        stream_in_32_TVALID => stream_in_32_TVALID_int_regslice,
        stream_in_32_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_in_32_TREADY,
        stream_in_32_TKEEP => stream_in_32_TKEEP_int_regslice,
        stream_in_32_TSTRB => stream_in_32_TSTRB_int_regslice,
        stream_in_32_TUSER => stream_in_32_TUSER_int_regslice,
        stream_in_32_TLAST => stream_in_32_TLAST_int_regslice,
        stream_out_24_TDATA => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TDATA,
        stream_out_24_TVALID => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID,
        stream_out_24_TKEEP => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TKEEP,
        stream_out_24_TSTRB => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TSTRB,
        stream_out_24_TUSER => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TUSER,
        stream_out_24_TLAST => grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TLAST);

    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104 : component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_68_7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start,
        ap_done => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_done,
        ap_idle => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_idle,
        ap_ready => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_ready,
        stream_out_24_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TREADY,
        stream_in_32_TDATA => stream_in_32_TDATA_int_regslice,
        stream_in_32_TVALID => stream_in_32_TVALID_int_regslice,
        stream_in_32_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_in_32_TREADY,
        stream_in_32_TKEEP => stream_in_32_TKEEP_int_regslice,
        stream_in_32_TSTRB => stream_in_32_TSTRB_int_regslice,
        stream_in_32_TUSER => stream_in_32_TUSER_int_regslice,
        stream_in_32_TLAST => stream_in_32_TLAST_int_regslice,
        stream_out_24_TDATA => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TDATA,
        stream_out_24_TVALID => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID,
        stream_out_24_TKEEP => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TKEEP,
        stream_out_24_TSTRB => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TSTRB,
        stream_out_24_TUSER => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TUSER,
        stream_out_24_TLAST => grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TLAST);

    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128 : component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_51_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start,
        ap_done => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_done,
        ap_idle => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_idle,
        ap_ready => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_ready,
        stream_out_24_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TREADY,
        stream_in_32_TDATA => stream_in_32_TDATA_int_regslice,
        stream_in_32_TVALID => stream_in_32_TVALID_int_regslice,
        stream_in_32_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_in_32_TREADY,
        stream_in_32_TKEEP => stream_in_32_TKEEP_int_regslice,
        stream_in_32_TSTRB => stream_in_32_TSTRB_int_regslice,
        stream_in_32_TUSER => stream_in_32_TUSER_int_regslice,
        stream_in_32_TLAST => stream_in_32_TLAST_int_regslice,
        stream_out_24_TDATA => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TDATA,
        stream_out_24_TVALID => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID,
        stream_out_24_TKEEP => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TKEEP,
        stream_out_24_TSTRB => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TSTRB,
        stream_out_24_TUSER => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TUSER,
        stream_out_24_TLAST => grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TLAST);

    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152 : component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_40_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start,
        ap_done => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_done,
        ap_idle => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_idle,
        ap_ready => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_ready,
        stream_in_32_TVALID => stream_in_32_TVALID_int_regslice,
        stream_out_24_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TREADY,
        stream_in_32_TDATA => stream_in_32_TDATA_int_regslice,
        stream_in_32_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_in_32_TREADY,
        stream_in_32_TKEEP => stream_in_32_TKEEP_int_regslice,
        stream_in_32_TSTRB => stream_in_32_TSTRB_int_regslice,
        stream_in_32_TUSER => stream_in_32_TUSER_int_regslice,
        stream_in_32_TLAST => stream_in_32_TLAST_int_regslice,
        stream_out_24_TDATA => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TDATA,
        stream_out_24_TVALID => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID,
        stream_out_24_TKEEP => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TKEEP,
        stream_out_24_TSTRB => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TSTRB,
        stream_out_24_TUSER => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TUSER,
        stream_out_24_TLAST => grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TLAST);

    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176 : component pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_19_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start,
        ap_done => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_done,
        ap_idle => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_idle,
        ap_ready => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_ready,
        stream_out_24_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TREADY,
        stream_in_32_TDATA => stream_in_32_TDATA_int_regslice,
        stream_in_32_TVALID => stream_in_32_TVALID_int_regslice,
        stream_in_32_TREADY => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_in_32_TREADY,
        stream_in_32_TKEEP => stream_in_32_TKEEP_int_regslice,
        stream_in_32_TSTRB => stream_in_32_TSTRB_int_regslice,
        stream_in_32_TUSER => stream_in_32_TUSER_int_regslice,
        stream_in_32_TLAST => stream_in_32_TLAST_int_regslice,
        stream_out_24_TDATA => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TDATA,
        stream_out_24_TVALID => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID,
        stream_out_24_TKEEP => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TKEEP,
        stream_out_24_TSTRB => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TSTRB,
        stream_out_24_TUSER => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TUSER,
        stream_out_24_TLAST => grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TLAST);

    control_s_axi_U : component pixel_unpack_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        mode => mode,
        ap_local_deadlock => ap_local_deadlock);

    regslice_both_stream_in_32_V_data_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_32_TDATA,
        vld_in => stream_in_32_TVALID,
        ack_in => regslice_both_stream_in_32_V_data_V_U_ack_in,
        data_out => stream_in_32_TDATA_int_regslice,
        vld_out => stream_in_32_TVALID_int_regslice,
        ack_out => stream_in_32_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_32_V_data_V_U_apdone_blk);

    regslice_both_stream_in_32_V_keep_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_32_TKEEP,
        vld_in => stream_in_32_TVALID,
        ack_in => regslice_both_stream_in_32_V_keep_V_U_ack_in,
        data_out => stream_in_32_TKEEP_int_regslice,
        vld_out => regslice_both_stream_in_32_V_keep_V_U_vld_out,
        ack_out => stream_in_32_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_32_V_keep_V_U_apdone_blk);

    regslice_both_stream_in_32_V_strb_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_32_TSTRB,
        vld_in => stream_in_32_TVALID,
        ack_in => regslice_both_stream_in_32_V_strb_V_U_ack_in,
        data_out => stream_in_32_TSTRB_int_regslice,
        vld_out => regslice_both_stream_in_32_V_strb_V_U_vld_out,
        ack_out => stream_in_32_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_32_V_strb_V_U_apdone_blk);

    regslice_both_stream_in_32_V_user_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_32_TUSER,
        vld_in => stream_in_32_TVALID,
        ack_in => regslice_both_stream_in_32_V_user_V_U_ack_in,
        data_out => stream_in_32_TUSER_int_regslice,
        vld_out => regslice_both_stream_in_32_V_user_V_U_vld_out,
        ack_out => stream_in_32_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_32_V_user_V_U_apdone_blk);

    regslice_both_stream_in_32_V_last_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_in_32_TLAST,
        vld_in => stream_in_32_TVALID,
        ack_in => regslice_both_stream_in_32_V_last_V_U_ack_in,
        data_out => stream_in_32_TLAST_int_regslice,
        vld_out => regslice_both_stream_in_32_V_last_V_U_vld_out,
        ack_out => stream_in_32_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_in_32_V_last_V_U_apdone_blk);

    regslice_both_stream_out_24_V_data_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_out_24_TDATA_int_regslice,
        vld_in => stream_out_24_TVALID_int_regslice,
        ack_in => stream_out_24_TREADY_int_regslice,
        data_out => stream_out_24_TDATA,
        vld_out => regslice_both_stream_out_24_V_data_V_U_vld_out,
        ack_out => stream_out_24_TREADY,
        apdone_blk => regslice_both_stream_out_24_V_data_V_U_apdone_blk);

    regslice_both_stream_out_24_V_keep_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_out_24_TKEEP_int_regslice,
        vld_in => stream_out_24_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_24_V_keep_V_U_ack_in_dummy,
        data_out => stream_out_24_TKEEP,
        vld_out => regslice_both_stream_out_24_V_keep_V_U_vld_out,
        ack_out => stream_out_24_TREADY,
        apdone_blk => regslice_both_stream_out_24_V_keep_V_U_apdone_blk);

    regslice_both_stream_out_24_V_strb_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_out_24_TSTRB_int_regslice,
        vld_in => stream_out_24_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_24_V_strb_V_U_ack_in_dummy,
        data_out => stream_out_24_TSTRB,
        vld_out => regslice_both_stream_out_24_V_strb_V_U_vld_out,
        ack_out => stream_out_24_TREADY,
        apdone_blk => regslice_both_stream_out_24_V_strb_V_U_apdone_blk);

    regslice_both_stream_out_24_V_user_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_out_24_TUSER_int_regslice,
        vld_in => stream_out_24_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_24_V_user_V_U_ack_in_dummy,
        data_out => stream_out_24_TUSER,
        vld_out => regslice_both_stream_out_24_V_user_V_U_vld_out,
        ack_out => stream_out_24_TREADY,
        apdone_blk => regslice_both_stream_out_24_V_user_V_U_apdone_blk);

    regslice_both_stream_out_24_V_last_V_U : component pixel_unpack_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => stream_out_24_TLAST_int_regslice,
        vld_in => stream_out_24_TVALID_int_regslice,
        ack_in => regslice_both_stream_out_24_V_last_V_U_ack_in_dummy,
        data_out => stream_out_24_TLAST,
        vld_out => regslice_both_stream_out_24_V_last_V_U_vld_out,
        ack_out => stream_out_24_TREADY,
        apdone_blk => regslice_both_stream_out_24_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_74_p2 = ap_const_lv32_0))) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_ready = ap_const_logic_1)) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_74_p2 = ap_const_lv32_1))) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_ready = ap_const_logic_1)) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_74_p2 = ap_const_lv32_2))) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_ready = ap_const_logic_1)) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_74_p2 = ap_const_lv32_3))) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_ready = ap_const_logic_1)) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_74_p2 = ap_const_lv32_4))) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_ready = ap_const_logic_1)) then 
                    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    mode_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((mode_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (mode_0_vld_reg = ap_const_logic_1)) or ((ap_const_logic_1 = ap_const_logic_1) and (mode_0_vld_reg = ap_const_logic_0)))) then
                mode_0_data_reg <= mode;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                mode_read_reg_200 <= mode_0_data_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (grp_read_fu_74_p2, mode_read_reg_200, ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_stream_out_24_V_data_V_U_apdone_blk, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if ((not((grp_read_fu_74_p2 = ap_const_lv32_0)) and not((grp_read_fu_74_p2 = ap_const_lv32_1)) and not((grp_read_fu_74_p2 = ap_const_lv32_2)) and not((grp_read_fu_74_p2 = ap_const_lv32_3)) and not((grp_read_fu_74_p2 = ap_const_lv32_4)) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done) and ((mode_read_reg_200 = ap_const_lv32_0) or ((mode_read_reg_200 = ap_const_lv32_1) or ((mode_read_reg_200 = ap_const_lv32_2) or ((mode_read_reg_200 = ap_const_lv32_3) or (mode_read_reg_200 = ap_const_lv32_4))))))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_stream_out_24_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(regslice_both_stream_out_24_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_stream_out_24_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(mode_read_reg_200, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_done, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_done, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_done, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_done, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_done)
    begin
                ap_block_state3_on_subcall_done <= (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_done = ap_const_logic_0) and (mode_read_reg_200 = ap_const_lv32_3)) or ((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_done = ap_const_logic_0) and (mode_read_reg_200 = ap_const_lv32_4)) or ((mode_read_reg_200 = ap_const_lv32_0) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_done = ap_const_logic_0)) or ((mode_read_reg_200 = ap_const_lv32_1) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_done = ap_const_logic_0)) or ((mode_read_reg_200 = ap_const_lv32_2) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_done = ap_const_logic_0)));
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_lv1_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start <= grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_ap_start_reg;
    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TREADY <= (stream_out_24_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start <= grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_ap_start_reg;
    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TREADY <= (stream_out_24_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start <= grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_ap_start_reg;
    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TREADY <= (stream_out_24_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start <= grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_ap_start_reg;
    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TREADY <= (stream_out_24_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start <= grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_ap_start_reg;
    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TREADY <= (stream_out_24_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_read_fu_74_p2 <= mode_0_data_reg;

    mode_0_ack_out_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, regslice_both_stream_out_24_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_stream_out_24_V_data_V_U_apdone_blk = ap_const_logic_0)))) then 
            mode_0_ack_out <= ap_const_logic_1;
        else 
            mode_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    stream_in_32_TREADY <= regslice_both_stream_in_32_V_data_V_U_ack_in;

    stream_in_32_TREADY_int_regslice_assign_proc : process(mode_read_reg_200, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_in_32_TREADY, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_in_32_TREADY, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_in_32_TREADY, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_in_32_TREADY, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_in_32_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((mode_read_reg_200 = ap_const_lv32_0)) then 
                stream_in_32_TREADY_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_in_32_TREADY;
            elsif ((mode_read_reg_200 = ap_const_lv32_1)) then 
                stream_in_32_TREADY_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_in_32_TREADY;
            elsif ((mode_read_reg_200 = ap_const_lv32_2)) then 
                stream_in_32_TREADY_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_in_32_TREADY;
            elsif ((mode_read_reg_200 = ap_const_lv32_3)) then 
                stream_in_32_TREADY_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_in_32_TREADY;
            elsif ((mode_read_reg_200 = ap_const_lv32_4)) then 
                stream_in_32_TREADY_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_in_32_TREADY;
            else 
                stream_in_32_TREADY_int_regslice <= ap_const_logic_0;
            end if;
        else 
            stream_in_32_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    stream_out_24_TDATA_int_regslice_assign_proc : process(mode_read_reg_200, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TDATA, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TDATA, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TDATA, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TDATA, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TDATA, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((mode_read_reg_200 = ap_const_lv32_0) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TDATA_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TDATA;
            elsif (((mode_read_reg_200 = ap_const_lv32_1) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TDATA_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TDATA;
            elsif (((mode_read_reg_200 = ap_const_lv32_2) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TDATA_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TDATA;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_3))) then 
                stream_out_24_TDATA_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TDATA;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_4))) then 
                stream_out_24_TDATA_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TDATA;
            else 
                stream_out_24_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            stream_out_24_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stream_out_24_TKEEP_int_regslice_assign_proc : process(mode_read_reg_200, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TKEEP, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TKEEP, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TKEEP, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TKEEP, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TKEEP, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((mode_read_reg_200 = ap_const_lv32_0) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TKEEP_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TKEEP;
            elsif (((mode_read_reg_200 = ap_const_lv32_1) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TKEEP_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TKEEP;
            elsif (((mode_read_reg_200 = ap_const_lv32_2) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TKEEP_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TKEEP;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_3))) then 
                stream_out_24_TKEEP_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TKEEP;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_4))) then 
                stream_out_24_TKEEP_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TKEEP;
            else 
                stream_out_24_TKEEP_int_regslice <= "XXX";
            end if;
        else 
            stream_out_24_TKEEP_int_regslice <= "XXX";
        end if; 
    end process;


    stream_out_24_TLAST_int_regslice_assign_proc : process(mode_read_reg_200, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TLAST, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TLAST, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TLAST, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TLAST, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TLAST, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((mode_read_reg_200 = ap_const_lv32_0) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TLAST_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TLAST;
            elsif (((mode_read_reg_200 = ap_const_lv32_1) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TLAST_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TLAST;
            elsif (((mode_read_reg_200 = ap_const_lv32_2) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TLAST_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TLAST;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_3))) then 
                stream_out_24_TLAST_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TLAST;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_4))) then 
                stream_out_24_TLAST_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TLAST;
            else 
                stream_out_24_TLAST_int_regslice <= "X";
            end if;
        else 
            stream_out_24_TLAST_int_regslice <= "X";
        end if; 
    end process;


    stream_out_24_TSTRB_int_regslice_assign_proc : process(mode_read_reg_200, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TSTRB, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TSTRB, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TSTRB, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TSTRB, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TSTRB, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((mode_read_reg_200 = ap_const_lv32_0) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TSTRB_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TSTRB;
            elsif (((mode_read_reg_200 = ap_const_lv32_1) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TSTRB_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TSTRB;
            elsif (((mode_read_reg_200 = ap_const_lv32_2) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TSTRB_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TSTRB;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_3))) then 
                stream_out_24_TSTRB_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TSTRB;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_4))) then 
                stream_out_24_TSTRB_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TSTRB;
            else 
                stream_out_24_TSTRB_int_regslice <= "XXX";
            end if;
        else 
            stream_out_24_TSTRB_int_regslice <= "XXX";
        end if; 
    end process;


    stream_out_24_TUSER_int_regslice_assign_proc : process(mode_read_reg_200, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TUSER, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TUSER, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TUSER, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TUSER, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TUSER, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((mode_read_reg_200 = ap_const_lv32_0) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TUSER_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TUSER;
            elsif (((mode_read_reg_200 = ap_const_lv32_1) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TUSER_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TUSER;
            elsif (((mode_read_reg_200 = ap_const_lv32_2) and (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID = ap_const_logic_1))) then 
                stream_out_24_TUSER_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TUSER;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_3))) then 
                stream_out_24_TUSER_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TUSER;
            elsif (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID = ap_const_logic_1) and (mode_read_reg_200 = ap_const_lv32_4))) then 
                stream_out_24_TUSER_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TUSER;
            else 
                stream_out_24_TUSER_int_regslice <= "X";
            end if;
        else 
            stream_out_24_TUSER_int_regslice <= "X";
        end if; 
    end process;

    stream_out_24_TVALID <= regslice_both_stream_out_24_V_data_V_U_vld_out;

    stream_out_24_TVALID_int_regslice_assign_proc : process(mode_read_reg_200, grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID, grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((mode_read_reg_200 = ap_const_lv32_0)) then 
                stream_out_24_TVALID_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_176_stream_out_24_TVALID;
            elsif ((mode_read_reg_200 = ap_const_lv32_1)) then 
                stream_out_24_TVALID_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_152_stream_out_24_TVALID;
            elsif ((mode_read_reg_200 = ap_const_lv32_2)) then 
                stream_out_24_TVALID_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_128_stream_out_24_TVALID;
            elsif ((mode_read_reg_200 = ap_const_lv32_3)) then 
                stream_out_24_TVALID_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_104_stream_out_24_TVALID;
            elsif ((mode_read_reg_200 = ap_const_lv32_4)) then 
                stream_out_24_TVALID_int_regslice <= grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_80_stream_out_24_TVALID;
            else 
                stream_out_24_TVALID_int_regslice <= ap_const_logic_0;
            end if;
        else 
            stream_out_24_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
